travis:
  secure:
    BINSTAR_TOKEN: p99a4r/XysIl1C23ZteOwfFIkCC5kDEgd0DXZu3evE8x7M/k7wi+0rwvV+kmLSX/MTtYsdDEkLJpyKxBklcG59SudIuo7/JXo37OQro8p4+4eJh3gJ/MH++qYE6LXfr9CNNMOMQYr1tQEFesLoQWZYo/Ittzcnpnz7EA/ifWx0ylQlQiKh1/IRWa+/2fJaeujiY+sfidFDFqHUyvBApjLfIw5ZEKRY4KJUSkwX+hqKB+mlPjfO0eEmPJtCmtoBeoO1Bntjh3b4sCu3gCb0xjpLmHpoUS2r2smi7SedNxTqkpqnkrkvyPgB6XO55Xc7Zg0Hwddx2OUcrdwiJeMiitoZuVEwFGBXS7/O7BsMAbKX/vhoEqUejxW14CNTjiNQ0pzLLaB4dfGWrgqZr3VMqSAi2SuK7dsQhOXqubJkypQgG8ln6SL0M+zPZK91lfEptPYxCd12LCUfb4J34x5ISrNZR2jEOSgm51uxhKPI/LYcS4cvzX0MnG0UyoUyW4rdvjTecyXIC235+StULam1wkOSksnhsCik01HRV/F+Gp8r6YBCndtPSWQWyZzvfvWuIvdIwbad9W5nUNgLDHy8mHeKUpFdDaWmyhdXadyJGtJFpOJ8AssRAX2XUYqi/CeI4aoz1kz79VVhMebPsjdzBgjQ7bsS5PUM/AKsgQu3K50Mc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
